trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar Cloud'
    organization: 'ravelly'
    scannerMode: 'Other'
- task: JMeterInstaller@0
  inputs:
    jmeterVersion: '5.4.2'

- task: Docker@2
  inputs:
      containerRegistry: 'Docker'
      command: 'login'

- task: Docker@2
  inputs:
      containerRegistry: 'Docker'
      repository: 'ravelly/devops'
      command: 'build'
      Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
      containerRegistry: 'Docker'
      repository: 'ravelly/devops'
- task: Kubernetes@1
  inputs:
    connectionType: 'None'
    command: 'apply'
    arguments: '-f deployment app.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    
    command: 'push'

- job: DeployLoadTesting
  dependsOn: Building
  pool: 'default'
  
- task: Kubernetes@1
  inputs:
      connectionType: 'None'
      command: 'apply'
      arguments: '-f deployment app.yaml'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'

- script: kubectl port-forward deploy/Test-deployment 8086:8085