name: CI/CD Trabajo Final
on: [workflow_dispatch, push]
concurrency: ci-app-${{ github.ref }}
jobs:
    build:
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
  
      - name: Build with Gradle
        run: ./gradlew build
  
      - name: Test with Gradle
        run: ./gradlew test
  
      - name: Publish Unit Test Results
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-results
          path: '**/build/reports/tests/test/index.html'
  
    #   - name: Code Quality and Security
    #     uses: sonarsource/sonarcloud-github-action@master
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}